version: '3.4'

# For Docker Desktop set switch to release

services:
  taxcalculatorapi:
    image: ${DOCKER_REGISTRY-}taxcalculatorapi
    restart: unless-stopped
    build:
      context: .
      dockerfile: TaxCalculatorAPI/Dockerfile
    volumes:
      - ./ssl/cert.cer:/https/cert.cer
      - ./ssl/key.key:/https/key.key

      # Overriding when runing on server
      - /root/ssl/cert.cer:/https/cert.cer
      - /root/ssl/key.key:/https/key.key
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:43721
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.cer 
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/key.key
    networks:
        - taxnetwork


  taxcalculatorblazorserver:
    image: ${DOCKER_REGISTRY-}taxcalculatorblazorserver
    restart: unless-stopped
    build:
      context: .
      dockerfile: TaxCalculatorBlazorServer/Dockerfile
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./ssl/cert.cer:/https/cert.cer
      - ./ssl/key.key:/https/key.key

      # Overriding when runing on server
      - /root/ssl/cert.cer:/https/cert.cer
      - /root/ssl/key.key:/https/key.key
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - API_URL=http://taxcalculatorapi:43721
      - ASPNETCORE_URLS=http://+80;https://+443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.cer
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/key.key
      
      # This line only when haveing a password protected certificate
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=IHR_PASSWORT
    networks:
        - taxnetwork

networks:
  taxnetwork: