version: '3.4'

services:
  taxcalculatorapi:
    image: ${DOCKER_REGISTRY-}taxcalculatorapi
    build:
      context: .
      dockerfile: TaxCalculatorAPI/Dockerfile
    volumes:
      - ./SSL/myserver.crt:/https/myserver.crt
      - ./SSL/myserver.key:/https/myserver.key
      # - /root/ssl/cert.cer:/https/cert.cer
      # - /root/ssl/key.key:/https/key.key
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/myserver.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/myserver.key
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.cer
      # - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/key.key
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:43721
    networks:
        - taxnetwork


  taxcalculatorblazorserver:
    image: ${DOCKER_REGISTRY-}taxcalculatorblazorserver
    build:
      context: .
      dockerfile: TaxCalculatorBlazorServer/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./SSL/myserver.crt:/https/myserver.crt
      - ./SSL/myserver.key:/https/myserver.key
      # - /root/ssl/cert.cer:/https/cert.cer
      # - /root/ssl/key.key:/https/key.key
    environment:
      - ASPNETCORE_URLS=https://+443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/myserver.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/myserver.key
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.cer
      # - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/key.key
      # This line only when haveing a password protected certificate
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=IHR_PASSWORT
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://taxcalculatorapi:43721
    networks:
        - taxnetwork

networks:
  taxnetwork: